### ISSUE TITLE
Plugin undefined

### ISSUE THREAD

**Issue by afeezaziz** [pbreuss/wikitude-ionic-2-starter-app#1]
Hi @pbreuss ,

Thanks for making this starter app. I am looking forward to try it but I am stuck at the beginning where I receive this log error:

EXCEPTION: Uncaught (in promise): ReferenceError: WikitudePlugin is not defined

Appreciate if you could give me pointers for this.

**Comment by afeezaziz** [comment]
Shouldn't use browser as it won't be detected.

**Comment by masonjeffreys** [comment]
@afeezaziz Can you clarify how you fixed this error? I'm seeing the same thing. Thanks!

*** Nevermind - you were simply saying that this error is to be expected if you try to use "ionic serve" to preview the app in the browser.

After I ran it on my device, everything is A-OK. Thanks!
