### ISSUE TITLE
Native api for instant tracking

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [pbreuss/wikitude-ionic-2-starter-app#10]
Hi,

I'm newone to wikitude.

In "ar-view.ts" file

You were using ["ir"] for image recognition world and ["geo"] for geo location world.

I don't know what i use for instant tracking image world.

could you please assist me

**Comment by pbreuss** [comment]
Hi,
You use "ir", because instant tracking is ir as well.
Regards,
Philipp 

Von meinem iPhone gesendet

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Thank you pbreuss.

I need to track an object in real time without using an target collection (WTC or WTO file).

Is this possible?

If it's possible let me know how to do this

**Comment by pbreuss** [comment]
I believe you can do this - it's called instant tracking - you have to "record" the object first - please refer to the wikitude website.
Regards,
Philipp 

Von meinem iPhone gesendet

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Thanks a lot.

Could you please clearify one more question

In image recognition world, after we track the image i have to pass that image into our ionic ts file and do some process with that image.

How to pass that image?


Regards
Mohamed Ismail
