### ISSUE TITLE
Communication between AR View and Ionic App doesn't work

### ISSUE THREAD

**Issue by dgoecke2** [pbreuss/wikitude-ionic-2-starter-app#11]
I've run these steps:
ionic cordova start WikitudeIonic2StarterApp
ionic cordova platform add ios
ionic cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git
Added my wikitude trial key to app.component.js
npm install
ionic cordova build ios

Setup signing and provision settings in Xcode. The app runs on my iPad mini iOS 11.1, however, when I click on snapshot nothing happens. The communication between the AR View and the Ionic app is not happening. I did not change anything in the app other than the commands above. Please let me know if there's something I am doing wrong. Otherwise, the communication is not happening correctly.

**Comment by pbreuss** [comment]
Hello Danika,
I'll test it and get back to you.
Best,
Philipp

Von meinem iPhone gesendet

**Comment by dgoecke2** [comment]
I believe I got it fixed now. I have it only working with tab view right now. I will get it integrated in working in my app flow. Thank you.

**Comment by dgwikitude** [comment]
Have you had issues with the WikitudePlugin.setOnUrlInvokeCallback and WikitudePlugin.setJSONObjectReceivedCallback functions taking a long time and multiple clicks to trigger? The click event works immediately in the interactivity.js file, then runs document.location = "architectsdk://button?action=goBack". The functions don't register sometimes for 20-30 seconds or until i've clicked the HTML element multiple times. Have you experienced this or have any ideas on how to fix it?
