### ISSUE TITLE
Not working - blank page

### ISSUE THREAD

**Issue by shaneparsons** [pbreuss/wikitude-ionic-2-starter-app#2]
I followed the instructions exactly and all I'm getting is a blank page. I'm testing on Android btw.

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by pbreuss** [comment]
I did not try it yet with Ionic Framework Version 3.0.0, which you are using. I guess something has changed and there is a compile error. Can you have a look at the ionic 2 code of your app to see if there is a compile error? Also, please look at https://github.com/driftyco/ionic/blob/master/CHANGELOG.md for the latest changes in ionic 2 (3.0.0). This is usually an easy fix - I'll look at it tomorrow.

I usually fix this by creating a blank ionic 2 app and, then compare the code with

**Comment by afeezaziz** [comment]
Hi @pbreuss and @shaneparsons  , I am facing the same problem too but on iOS.

Because you are using Ionic 3.0.0, you need to import and add BrowserModule in your app.module.ts. Then, you can rebuild and it will be ok. Please try it and let me know if it is ok.

**Comment by shaneparsons** [comment]
@afeezaziz Thanks man, that worked for me.
