### ISSUE TITLE
Not working - blank page

### ISSUE THREAD

**Issue by rrubio** [pbreuss/wikitude-ionic-2-starter-app#8]
Hi Guys,

As per previous issue "app.module.ts" already contains "BrowserModule". My page still blank under IOS. Any ideas?

Cheers

**Comment by rrubio** [comment]
Got it working. I needed to update my package.json "dependencies"

        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "4.1.0",
        "@ionic-native/device": "^4.2.0",
        "@ionic-native/splash-screen": "4.1.0",
        "@ionic-native/status-bar": "4.1.0",
        "@ionic/storage": "2.0.1",

**Comment by pbreuss** [comment]
Cool!

2017-08-28 15:17 GMT+02:00 Rodrigo Rubio <notifications@github.com>:
